# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"NB_VERSION": "00_cli.ipynb",
         "extract": "00_cli.ipynb"}

modules = ["cli.py"]

doc_url = "https://wooduk.github.io/fastbook_questions/"

git_url = "https://github.com/wooduk/fastbook_questions/tree/master/"

def custom_doc_links(name): return None
